[build]
  command = "echo 'build done'"
  functions = "netlify/functions"
  publish = "_site"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200
